"""
Generate the golden evaluation set (200 hand-labelled examples).
Run: python scripts/generate_golden_set.py
"""
import json, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import config

examples = []
_id = 0

def add(msg, intent, esc, esc_reason, diff="medium", ctx=None, ref_reply=None):
    global _id
    _id += 1
    examples.append({
        "id": f"gs_{_id:03d}",
        "customer_message": msg,
        "conversation_context": ctx or [],
        "gold_intent": intent,
        "gold_escalation": esc,
        "gold_escalation_reason": esc_reason,
        "difficulty": diff,
        "reference_reply": ref_reply or ""
    })

# ── device_issue (20) ──
add("My iPhone screen cracked and now touch doesn't work at all", "device_issue", "escalate", "Physical damage needs in-person assessment", "easy")
add("The charging port on my MacBook Pro is loose and keeps disconnecting", "device_issue", "escalate", "Hardware repair needed", "easy")
add("My iPhone 13 gets extremely hot when I'm just browsing", "device_issue", "auto_handle", "Standard troubleshooting steps available", "easy")
add("Speaker on my iPhone sounds muffled and distorted during calls", "device_issue", "auto_handle", "Basic speaker troubleshooting", "easy")
add("Home button on my iPad completely stopped working yesterday", "device_issue", "escalate", "Hardware component failure", "easy")
add("My Apple Watch screen has a green line running down it", "device_issue", "escalate", "Display hardware defect", "medium")
add("Camera on my iPhone makes a clicking noise and photos are blurry", "device_issue", "escalate", "Camera module likely needs replacement", "medium")
add("My MacBook keyboard has sticky keys after a small spill", "device_issue", "escalate", "Liquid damage requires physical inspection", "medium")
add("iPhone vibration motor feels weird, like it's grinding", "device_issue", "auto_handle", "Can try settings reset first", "medium")
add("My AirPods case won't charge even with different cables", "device_issue", "auto_handle", "Standard AirPods troubleshooting first", "medium")
add("The trackpad on my MacBook sometimes registers phantom clicks", "device_issue", "auto_handle", "Could be software, try SMC reset", "medium")
add("My iPad Pro bent slightly in my bag and now the screen flickers", "device_issue", "escalate", "Physical damage and display issue", "medium")
add("iPhone 14 just randomly restarts when I make phone calls. Hardware?", "device_issue", "auto_handle", "Could be software issue, needs diagnosis", "hard")
add("tbh my phone just died. won't turn on. bought it 2 weeks ago", "device_issue", "escalate", "New device failure within warranty", "hard")
add("my macbook makes this weird fan noise even when doing nothing. is this normal???", "device_issue", "auto_handle", "Can check Activity Monitor first", "hard")
add("Bruh my iphone screen turned green after the update... is this a hardware thing or software??", "device_issue", "auto_handle", "Likely software; try restart first", "hard")
add("So my phone overheats, battery drains fast, AND the speaker crackles. Everything broke at once??", "device_issue", "escalate", "Multiple simultaneous hardware issues", "hard")
add("Dropped my phone in water yesterday. Worked fine until today morning now screen is glitching", "device_issue", "escalate", "Water damage requires inspection", "easy")
add("My lightning cable port has lint stuck in it and won't charge properly", "device_issue", "auto_handle", "User can clean port carefully", "easy")
add("The Face ID sensor on my iPhone stopped working completely", "device_issue", "escalate", "Sensor hardware failure", "medium")

# ── software_bug (20) ──
add("Ever since iOS 17 update my phone keeps freezing randomly", "software_bug", "auto_handle", "Standard post-update troubleshooting", "easy")
add("My Mac is stuck on the Apple logo and won't boot", "software_bug", "auto_handle", "Can guide through recovery mode", "easy")
add("FaceTime crashes every single time I try to make a video call", "software_bug", "auto_handle", "App reinstall/update may fix", "easy")
add("After updating to macOS Sonoma my external display stopped working", "software_bug", "auto_handle", "Known compatibility issue, workarounds exist", "easy")
add("My iPhone alarm didn't go off this morning! Made me late for work", "software_bug", "auto_handle", "Known iOS alarm bug", "easy")
add("Siri just stopped working after the last update. Says 'something went wrong' every time", "software_bug", "auto_handle", "Settings reset should fix", "medium")
add("My iMessages are showing up in the wrong order. Timestamps are all messed up", "software_bug", "auto_handle", "Date/time settings issue", "medium")
add("Safari keeps crashing on my iPad. Can't browse any website for more than 30 seconds", "software_bug", "auto_handle", "Clear cache and history", "medium")
add("Widgets on my home screen keep disappearing after every restart", "software_bug", "auto_handle", "Known bug, re-add after update", "medium")
add("My Apple Watch won't pair with my new iPhone after transfer", "software_bug", "auto_handle", "Unpair and re-pair process", "medium")
add("The keyboard autocorrect has gotten SO much worse after the update. It changes correct words!!", "software_bug", "auto_handle", "Reset keyboard dictionary", "medium")
add("My phone randomly restarted 5 times today. No pattern I can see", "software_bug", "auto_handle", "Check crash logs and update", "medium")
add("Got a 'unable to check for update' error. Tried everything. 3 days now", "software_bug", "auto_handle", "Network/storage troubleshooting", "hard")
add("icloud syncing is broken between all my devices. notes show on phone but not mac and vice versa", "software_bug", "auto_handle", "iCloud sync troubleshooting", "hard")
add("ok so my phone updated itself overnight and now half my apps are crashing. what did you guys do 😤", "software_bug", "auto_handle", "Post-update app compatibility", "hard")
add("is anyone else having the bug where the phone screen just goes black during calls?? started after update", "software_bug", "auto_handle", "Proximity sensor or software bug", "hard")
add("My iPad is stuck in a boot loop after trying to update. Can't even get to recovery mode", "software_bug", "escalate", "Boot loop requiring DFU mode assistance", "hard")
add("Lost all my photos after the iOS update. They're just GONE. Please help this is years of memories", "software_bug", "escalate", "Data loss is high severity", "easy")
add("Mail app notifications stopped working. I've missed important work emails", "software_bug", "auto_handle", "Notification settings reset", "medium")
add("My iPhone clock is showing wrong time even though set to automatic", "software_bug", "auto_handle", "Time zone settings fix", "easy")

# ── account_access (20) ──
add("I can't sign into my Apple ID. Says my account has been locked for security reasons", "account_access", "escalate", "Locked account needs identity verification", "easy")
add("Forgot my Apple ID password and the recovery email is an old one I don't have access to", "account_access", "escalate", "Account recovery with no email access", "easy")
add("Two-factor authentication code isn't arriving on any of my devices", "account_access", "escalate", "2FA failure locks user out completely", "easy")
add("Someone changed my Apple ID password and I think my account was hacked", "account_access", "escalate", "Security breach - immediate escalation", "easy")
add("I set up a new iPhone but it's asking for the previous owner's Apple ID to activate", "account_access", "escalate", "Activation lock requires ownership proof", "medium")
add("Can't remember my Apple ID email address at all. How do I find it?", "account_access", "auto_handle", "Can guide through iforgot.apple.com", "easy")
add("My kid set a screen time passcode and now even I can't change it", "account_access", "auto_handle", "Screen Time passcode recovery steps", "medium")
add("I keep getting 'verification failed' when trying to sign into iCloud", "account_access", "auto_handle", "Usually network or date/time issue", "medium")
add("Trying to create a new Apple ID but it says my email is already associated with another account", "account_access", "auto_handle", "Guide through account lookup", "medium")
add("My account says it's disabled in the App Store but I can use everything else fine??", "account_access", "escalate", "Partial account disable is unusual", "hard")
add("Just changed my password but it's still not letting me log in on my Mac", "account_access", "auto_handle", "Needs to update password on all devices", "easy")
add("I think someone is using my Apple ID. I'm seeing purchases I didn't make", "account_access", "escalate", "Unauthorized access and fraud", "easy")
add("Stuck in an activation lock loop after factory reset. I AM the owner", "account_access", "escalate", "Activation lock needs proof of purchase", "medium")
add("My child's Apple ID got locked because they entered the wrong password too many times", "account_access", "auto_handle", "Standard unlock process for child account", "medium")
add("can't log into anything apple related. id, icloud, app store. all say error connecting", "account_access", "auto_handle", "Likely network/server issue", "hard")
add("I have my receipt and everything but the activation lock won't come off. been trying for a week now", "account_access", "escalate", "Persistent activation lock with proof of purchase", "hard")
add("Changed my Apple ID email but now I can't access my old purchases", "account_access", "escalate", "Purchase history tied to old ID", "medium")
add("My Apple ID got disabled after I traveled abroad. I think it's a security thing?", "account_access", "escalate", "Account disabled during travel", "medium")
add("Getting asked for an Apple ID I've never seen before on this used iPhone I just bought", "account_access", "escalate", "Possible stolen device / activation lock", "easy")
add("Why does my Apple ID keep signing out on its own every few hours?", "account_access", "auto_handle", "Sign-out loop troubleshooting", "medium")

# ── billing_inquiry (20) ──
add("I was charged $9.99 for an app I never downloaded. Need a refund", "billing_inquiry", "escalate", "Unauthorized charge needs investigation", "easy")
add("How do I cancel my Apple Music subscription?", "billing_inquiry", "auto_handle", "Simple how-to for subscription management", "easy")
add("My kid made $200 worth of in-app purchases without my permission. Need refund ASAP", "billing_inquiry", "escalate", "Significant unauthorized purchases by minor", "easy")
add("I was double-charged for my iCloud storage this month", "billing_inquiry", "escalate", "Billing error needs backend investigation", "easy")
add("I cancelled my subscription but I'm still being charged every month", "billing_inquiry", "escalate", "Recurring charge after cancellation", "medium")
add("How much does iCloud 200GB cost per month?", "billing_inquiry", "auto_handle", "Simple pricing question", "easy")
add("I want to upgrade my iCloud storage plan from 50GB to 200GB", "billing_inquiry", "auto_handle", "Standard upgrade process", "easy")
add("Can I get a refund for an app that doesn't work as advertised?", "billing_inquiry", "auto_handle", "Direct to reportaproblem.apple.com", "medium")
add("I see a charge from 'apple.com/bill' on my credit card but I don't know what it's for", "billing_inquiry", "auto_handle", "Can check purchase history in settings", "medium")
add("My free trial ended and I got charged without any warning", "billing_inquiry", "auto_handle", "Trial terms are shown at signup", "medium")
add("Need to change my payment method for Apple subscriptions", "billing_inquiry", "auto_handle", "Simple settings change", "easy")
add("Got charged $14.99 for Apple TV+ but I thought it was included with my new iPhone", "billing_inquiry", "auto_handle", "Explain promo terms and expiry", "medium")
add("I've been charged for a subscription I cancelled 3 months ago. This is theft. I want my money back NOW", "billing_inquiry", "escalate", "Multiple months of incorrect charges, angry customer", "hard")
add("there's like 5 charges from apple on my bank statement this month and i only bought one thing", "billing_inquiry", "escalate", "Multiple unexplained charges", "hard")
add("how do i see what subscriptions i'm paying for? i think i'm paying for stuff i forgot about", "billing_inquiry", "auto_handle", "Guide to subscription management", "easy")
add("Trying to buy an app but it says my payment method was declined even though I have money", "billing_inquiry", "auto_handle", "Payment method verification", "medium")
add("I returned my iPhone but the AppleCare charge is still on my account", "billing_inquiry", "escalate", "Refund for returned product service plan", "medium")
add("why am i being charged in USD when I'm in the UK? my bank is adding conversion fees", "billing_inquiry", "auto_handle", "Regional pricing explanation", "hard")
add("I'm going to dispute these charges with my bank if you don't refund me", "billing_inquiry", "escalate", "Threat of chargeback - needs immediate attention", "hard")
add("Can I transfer my remaining Apple gift card balance to a different account?", "billing_inquiry", "auto_handle", "Gift card policy explanation", "medium")

# ── how_to (20) ──
add("How do I transfer all my data from my old iPhone to my new one?", "how_to", "auto_handle", "Standard how-to question", "easy")
add("Where can I find my iPhone's serial number?", "how_to", "auto_handle", "Simple settings lookup", "easy")
add("How do I set up Family Sharing with my wife's account?", "how_to", "auto_handle", "Feature setup guidance", "easy")
add("How do I take a screenshot on my new MacBook?", "how_to", "auto_handle", "Simple keyboard shortcut", "easy")
add("What's the best way to back up my iPhone before trading it in?", "how_to", "auto_handle", "Backup process guidance", "easy")
add("How do I use AirDrop to send photos to my friend's iPhone?", "how_to", "auto_handle", "AirDrop walkthrough", "easy")
add("Can I use my iPad as a second screen for my Mac? How?", "how_to", "auto_handle", "Sidecar feature setup", "medium")
add("How do I set up an email signature on the Mail app?", "how_to", "auto_handle", "Mail settings guidance", "easy")
add("Is there a way to schedule messages to send later on iPhone?", "how_to", "auto_handle", "Feature availability info", "medium")
add("How do I add a widget to my iPhone lock screen?", "how_to", "auto_handle", "iOS customization steps", "easy")
add("How can I track my AirPods location if I lost them?", "how_to", "auto_handle", "Find My setup and usage", "medium")
add("I want to set up parental controls on my kid's iPad. What's the best approach?", "how_to", "auto_handle", "Screen Time and restrictions", "medium")
add("how do i make my mac automatically lock when i walk away?", "how_to", "auto_handle", "Apple Watch auto-lock or sleep settings", "medium")
add("Is there a way to recover deleted texts from like 2 months ago?", "how_to", "auto_handle", "iCloud backup message recovery", "hard")
add("how do you set up that thing where your phone automatically goes to focus mode at night", "how_to", "auto_handle", "Focus mode scheduling", "medium")
add("Can I use two different Apple IDs on the same iPhone? One for iCloud and one for App Store?", "how_to", "auto_handle", "Yes, guide through settings", "hard")
add("How do I check my iPhone battery health percentage?", "how_to", "auto_handle", "Settings > Battery > Battery Health", "easy")
add("What do I do with my Apple Watch before selling it?", "how_to", "auto_handle", "Unpair and erase guide", "medium")
add("How to scan documents with my iPhone camera?", "how_to", "auto_handle", "Notes app scanner feature", "easy")
add("Is there a way to share my location with family members permanently?", "how_to", "auto_handle", "Find My or Messages sharing", "medium")

# ── app_issue (20) ──
add("I can't download any apps from the App Store. It just shows a spinning wheel forever", "app_issue", "auto_handle", "Clear cache, sign out/in", "easy")
add("WhatsApp won't update on my iPhone. Says 'unable to update'", "app_issue", "auto_handle", "Storage or network issue", "easy")
add("Apps keep crashing immediately after I open them since the update", "app_issue", "auto_handle", "Reinstall apps or update iOS", "easy")
add("My banking app says it's not compatible with my iOS version", "app_issue", "auto_handle", "Check iOS version requirements", "medium")
add("I accidentally deleted an app I paid for. Do I have to buy it again?", "app_issue", "auto_handle", "No, redownload from purchase history", "easy")
add("App Store keeps asking me to verify my payment info before downloading free apps", "app_issue", "auto_handle", "Update payment method", "medium")
add("The App Store page is completely blank. Just white screen", "app_issue", "auto_handle", "Clear cache, check network", "medium")
add("Instagram sends me notifications but when I open the app there's nothing new", "app_issue", "auto_handle", "Third-party app notification issue", "medium")
add("I downloaded an app that turned out to be a scam. It charged me $50/week", "app_issue", "escalate", "Scam app needs review and refund", "hard")
add("An app I paid $4.99 for was removed from the App Store. Can I still use it?", "app_issue", "auto_handle", "Already purchased apps remain", "medium")
add("My weather app widget stopped updating. Stuck on yesterday's forecast", "app_issue", "auto_handle", "Widget refresh troubleshooting", "easy")
add("Can't install TestFlight beta apps. Says 'unable to install'", "app_issue", "auto_handle", "TestFlight troubleshooting", "medium")
add("All my app subscriptions disappeared from settings after restoring my phone", "app_issue", "auto_handle", "Restore purchases or re-sign in", "medium")
add("An app keeps requesting microphone access even though I denied it. Is this a virus??", "app_issue", "auto_handle", "iOS permission prompts explanation", "hard")
add("The Podcasts app loses my progress and starts episodes from the beginning", "app_issue", "auto_handle", "App sync issue, reinstall", "easy")
add("I can't find a specific app in the App Store. Is it region locked?", "app_issue", "auto_handle", "Explain regional availability", "medium")
add("My phone storage says apps are using 40GB but I barely have any installed", "app_issue", "auto_handle", "Offloaded apps or cache data", "hard")
add("App downloads get stuck at 'Waiting...' and never actually download", "app_issue", "auto_handle", "Prioritize download or restart", "easy")
add("Just bought an app and it won't open. Immediately closes. Paid $12.99 for this!", "app_issue", "auto_handle", "Try reinstall, then refund if still broken", "medium")
add("A developer is threatening me through their app's messaging. This is harassment", "app_issue", "escalate", "Safety concern - report to Trust & Safety", "hard")

# ── connectivity (20) ──
add("My iPhone keeps disconnecting from WiFi every 5 minutes", "connectivity", "auto_handle", "Reset network settings", "easy")
add("Bluetooth won't pair with my car's audio system anymore", "connectivity", "auto_handle", "Remove and re-pair device", "easy")
add("AirDrop doesn't show my Mac as a device even though they're next to each other", "connectivity", "auto_handle", "AirDrop settings check", "easy")
add("My cellular data stopped working. Shows signal bars but no data", "connectivity", "auto_handle", "Toggle airplane mode, check APN", "easy")
add("WiFi works on all other devices but my iPhone says 'no internet connection'", "connectivity", "auto_handle", "Forget and rejoin network", "medium")
add("My AirPods keep disconnecting mid-call and reconnecting", "connectivity", "auto_handle", "Reset AirPods, re-pair", "medium")
add("Personal hotspot doesn't show up on my other devices", "connectivity", "auto_handle", "Hotspot settings and carrier check", "medium")
add("Can't connect to any 5G network even though my area has coverage", "connectivity", "auto_handle", "Check 5G settings and carrier plan", "medium")
add("My Mac loses ethernet connection randomly but WiFi works fine", "connectivity", "auto_handle", "Network preferences troubleshooting", "medium")
add("iMessage says 'waiting for activation' and it's been 3 days", "connectivity", "auto_handle", "Reset iMessage, check carrier", "medium")
add("My iPhone can't find any WiFi networks at all. The list is completely empty", "connectivity", "escalate", "Possible WiFi antenna hardware failure", "hard")
add("VPN disconnects every time my iPhone screen locks", "connectivity", "auto_handle", "VPN app settings or Low Power Mode", "medium")
add("since the update my phone drops calls after exactly 2 minutes every time. tested 10+ calls", "connectivity", "escalate", "Consistent call dropping pattern may be hardware", "hard")
add("Handoff between my iPhone and Mac stopped working. Already on same WiFi and iCloud", "connectivity", "auto_handle", "Sign out/in of iCloud on both", "medium")
add("My Apple TV keeps buffering even though speed test shows 200mbps", "connectivity", "auto_handle", "DNS or streaming quality settings", "medium")
add("eSIM transfer failed and now I have no cellular service on either phone", "connectivity", "escalate", "No cellular service - urgent connectivity issue", "hard")
add("bluetooth keyboard keeps typing wrong characters when connected to ipad", "connectivity", "auto_handle", "Input source/language settings", "hard")
add("CarPlay disconnects constantly. Tried 3 different cables already", "connectivity", "auto_handle", "Check car compatibility and port", "medium")
add("My HomePod can't connect to WiFi even though it's right next to the router", "connectivity", "auto_handle", "Reset HomePod and setup again", "easy")
add("FaceTime audio cuts out when I switch from WiFi to cellular and vice versa", "connectivity", "auto_handle", "WiFi Assist settings", "medium")

# ── performance (20) ──
add("My iPhone battery goes from 100% to 20% in just 3 hours of normal use", "performance", "auto_handle", "Battery health check and settings optimization", "easy")
add("My MacBook is incredibly slow. Takes 5 minutes just to open Finder", "performance", "auto_handle", "Activity Monitor check, storage/RAM", "easy")
add("I keep getting 'Storage Almost Full' even after deleting tons of photos", "performance", "auto_handle", "Clear 'Other' storage and cache", "easy")
add("My iPad is so laggy now. It used to be fast. Is it because it's old?", "performance", "auto_handle", "Clear RAM, reduce animations", "easy")
add("iPhone battery health shows 79%. Is that bad? Should I replace it?", "performance", "auto_handle", "Explain battery health thresholds", "easy")
add("My Mac fans run at full speed even when I'm just writing a document", "performance", "auto_handle", "Check Activity Monitor for runaway processes", "medium")
add("iPhone gets uncomfortably hot while charging. Like can barely hold it", "performance", "escalate", "Safety concern - overheating during charging", "medium")
add("My 2 year old MacBook Air only lasts 2 hours on battery now", "performance", "auto_handle", "Battery cycle count and health check", "medium")
add("Storage says 'System Data' is using 60GB on my 128GB iPhone. That can't be right", "performance", "auto_handle", "System data cache clearing steps", "medium")
add("My iPhone keeps dimming the screen even though auto-brightness is off", "performance", "auto_handle", "Thermal management explanation", "medium")
add("After the update my phone is noticeably slower. Apps take 3-4 seconds to open", "performance", "auto_handle", "Post-update indexing explanation", "medium")
add("RAM on my MacBook is always at 95%+ usage even with only 2 apps open", "performance", "auto_handle", "Memory management and swap usage", "medium")
add("my phone literally dies at 30% battery. just shuts off. every single day now", "performance", "escalate", "Battery shutting down early - possible hardware defect", "hard")
add("Is Apple throttling my old iPhone? It's gotten way slower after the update", "performance", "auto_handle", "Explain performance management feature", "hard")
add("my macbook crashed 3 times today. kernel panic every time. losing all my work", "performance", "escalate", "Repeated kernel panics indicate serious issue", "hard")
add("icloud sync is making my mac completely unusable. beach ball spinning for minutes", "performance", "auto_handle", "Pause sync, check what's syncing", "hard")
add("My iPhone 12 still perfectly fine but battery percentage jumps from 40 to 15 randomly", "performance", "escalate", "Battery calibration or cell failure", "medium")
add("Mac takes 10+ minutes to wake from sleep now", "performance", "auto_handle", "SMC/NVRAM reset for Intel Macs", "medium")
add("My M2 MacBook Air throttles during video calls. Screen gets choppy", "performance", "auto_handle", "Thermal throttling during intensive tasks", "medium")
add("Everything on my iPhone is delayed by half a second. Typing, scrolling, everything", "performance", "auto_handle", "Reduce Motion and restart", "easy")

# ── feedback_complaint (20) ──
add("I love the new iOS update! The interactive widgets are amazing 🎉", "feedback_complaint", "auto_handle", "Positive feedback - acknowledge", "easy")
add("Your support has been absolutely terrible. 3 hours on hold and no help", "feedback_complaint", "escalate", "Severe complaint about service quality", "easy")
add("Worst customer service experience of my life. Never buying Apple again", "feedback_complaint", "escalate", "Customer threatening to leave brand", "easy")
add("Just want to say thank you to the Apple team who fixed my Mac. Great service!", "feedback_complaint", "auto_handle", "Positive feedback", "easy")
add("Apple products used to be good. Quality has really gone downhill", "feedback_complaint", "auto_handle", "General product feedback", "easy")
add("I've been a loyal customer for 15 years and this is how you treat me?", "feedback_complaint", "escalate", "Loyalty mention + strong dissatisfaction", "medium")
add("Your prices are ridiculous. $1000 for a phone that breaks in a year", "feedback_complaint", "auto_handle", "Price complaint - no actionable issue", "medium")
add("Seriously considering switching to Samsung after this experience", "feedback_complaint", "escalate", "Churn risk signal", "medium")
add("The Genius Bar appointment system is broken. Earliest slot is 2 weeks out", "feedback_complaint", "auto_handle", "Appointment availability feedback", "medium")
add("Why does Apple force you to use their ecosystem for everything? It's so annoying", "feedback_complaint", "auto_handle", "Ecosystem complaint - general frustration", "medium")
add("Can you guys PLEASE add a calculator app to the iPad?? It's been 13 years!", "feedback_complaint", "auto_handle", "Feature request", "easy")
add("The new MacBook Pro is absolutely stunning. Best laptop I've ever owned", "feedback_complaint", "auto_handle", "Positive product feedback", "easy")
add("Every time I call support I get transferred 5 times and have to explain everything over and over", "feedback_complaint", "escalate", "Systemic support experience complaint", "hard")
add("I'm going to post about this terrible experience on every social media platform", "feedback_complaint", "escalate", "Threat of public complaint", "hard")
add("love my iphone but please make the volume buttons less clicky on the next model lol", "feedback_complaint", "auto_handle", "Minor product feedback", "easy")
add("3rd time sending my MacBook for repair. Same issue keeps coming back. Your repair quality is garbage", "feedback_complaint", "escalate", "Repeat repair failure - needs escalation", "hard")
add("The subscription prices keep going up but the quality stays the same 😒", "feedback_complaint", "auto_handle", "Pricing feedback", "medium")
add("I've recommended Apple to everyone I know. Keep up the great work!", "feedback_complaint", "auto_handle", "Positive referral feedback", "easy")
add("You guys need a better trade-in program. The values are insultingly low", "feedback_complaint", "auto_handle", "Trade-in program feedback", "medium")
add("honestly if the next iphone doesn't have usb-c i'm done with apple forever", "feedback_complaint", "auto_handle", "Feature demand (now resolved with USB-C)", "hard")

# ── other (20) ──
add("Hello!", "other", "auto_handle", "Simple greeting", "easy")
add("lol ok whatever", "other", "auto_handle", "Non-substantive message", "easy")
add("Can you help me fix my Samsung Galaxy?", "other", "auto_handle", "Non-Apple product query", "easy")
add("👍", "other", "auto_handle", "Emoji-only response", "easy")
add("Testing testing 123", "other", "auto_handle", "Non-support message", "easy")
add("What time does the Apple Store in NYC close?", "other", "auto_handle", "Store hours inquiry", "easy")
add("Is Apple going to release a new iPhone this year?", "other", "auto_handle", "Product rumor/speculation", "easy")
add("Do you guys sell refurbished MacBooks?", "other", "auto_handle", "General sales question", "easy")
add("Can I bring my dog to the Apple Store?", "other", "auto_handle", "Store policy question", "medium")
add("I just wanted to let you know your website is down", "other", "auto_handle", "Website status report", "medium")
add("Is there a student discount for MacBooks?", "other", "auto_handle", "Pricing/education inquiry", "easy")
add("My Windows laptop has a virus. Can you help?", "other", "auto_handle", "Non-Apple product", "easy")
add("Are you guys hiring? I'd love to work at Apple", "other", "auto_handle", "Employment inquiry", "easy")
add("(empty message)", "other", "auto_handle", "Empty/near-empty message", "easy")  # Edge case: tests graceful handling
add("@AppleSupport follow back pls 🙏", "other", "auto_handle", "Social media engagement, not support", "easy")
add("Hey can someone explain to me why Apple exists", "other", "auto_handle", "Philosophical/non-support question", "medium")
add("What happened to the Apple Car project?", "other", "auto_handle", "Corporate strategy question", "medium")
add("I need help but I don't even know where to start tbh", "other", "auto_handle", "Vague, needs clarification", "hard")
add("So I have a problem... it's kind of complicated... can someone DM me?", "other", "auto_handle", "Vague request for DM", "hard")
add("Apple Google Microsoft Amazon who's the best? Debate me", "other", "auto_handle", "Non-support engagement", "easy")

# ── Save ──
out = config.GOLDEN_SET_PATH
out.parent.mkdir(parents=True, exist_ok=True)
with open(out, "w", encoding="utf-8") as f:
    json.dump(examples, f, indent=2, ensure_ascii=False)
print(f"[OK] Generated {len(examples)} golden-set examples -> {out}")

# Stats
from collections import Counter
intents = Counter(e["gold_intent"] for e in examples)
diffs = Counter(e["difficulty"] for e in examples)
escs = Counter(e["gold_escalation"] for e in examples)
print(f"\nIntent distribution:  {dict(intents)}")
print(f"Difficulty distribution: {dict(diffs)}")
print(f"Escalation distribution: {dict(escs)}")
